name = "michigan-daily-alt-text-tracker"
main = "worker/index.ts"
compatibility_date = "2024-02-23"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 0 * * *"] # 0 0 * * * = run at the beginning of every day

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "michigan-daily-alt-text-tracker"
database_id = "90d3113e-ddda-4ab7-b7a3-d87ca2cf86e4"
preview_database_id = "DB" # Required for Pages local development